# Generated by Django 5.0.7 on 2026-05-14 12:48

import django.db.models.deletion
import drafts.models
import drafts.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField(choices=[(1, 'Chapter 1'), (2, 'Chapter 2'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5')], db_index=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to=drafts.models.draft_upload_path, validators=[drafts.validators.validate_draft_file])),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], db_index=True, default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='projects.researchproject')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['project', 'chapter', '-version'], name='drafts_draf_project_71c2bd_idx'), models.Index(fields=['status', 'submitted_at'], name='drafts_draf_status_5afcd4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='draftsubmission',
            constraint=models.UniqueConstraint(fields=('project', 'chapter', 'version'), name='unique_project_chapter_version'),
        ),
    ]
